spring:
  datasource:
    url: jdbc:mysql://localhost:3309/Micro_VoitureDB?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: SERVICE-VOITURE
  cloud:
    discovery:
      enabled: true
    consul:
      host: localhost
      port: 8500
      discovery: SERVICE-VOITURE
server:
  port: 8089
